apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mozhi-eks
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
