apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  creationTimestamp: null
  name: mozhitenant
  namespace: mozhi
scheduler:
  name: ""
spec:
  certConfig: {}
  credsSecret:
    name: mozhitenant-creds-secret
  image: minio/minio:RELEASE.2021-12-10T23-03-39Z
  imagePullSecret: {}
  mountPath: /export
  pools:
  - affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: v1.min.io/tenant
              operator: In
              values:
              - mozhitenant
          topologyKey: kubernetes.io/hostname
    resources: {}
    servers: 1
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
        storageClassName: standard
      status: {}
    volumesPerServer: 4
  requestAutoCert: false
  users:
  - name: mozhitenant-user-1
status:
  availableReplicas: 0
  certificates: {}
  currentState: ""
  pools: null
  revision: 0
  syncVersion: ""
  usage: {}

---
apiVersion: v1
data:
  accesskey: bW96aGk=
  secretkey: bW96aGkxMjM=
kind: Secret
metadata:
  creationTimestamp: null
  name: mozhitenant-creds-secret
  namespace: mozhi

---
apiVersion: v1
data:
  CONSOLE_ACCESS_KEY: YWRtaW4=
  CONSOLE_SECRET_KEY: bW96aGkxMjM=
kind: Secret
metadata:
  creationTimestamp: null
  name: mozhitenant-user-1
  namespace: mozhi

