apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: torchserve-pv-1
 namespace: mozhi
spec:
 persistentVolumeReclaimPolicy: Delete
 storageClassName: local-storage
 capacity:
   storage: 1Gi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: /Users/m.c.dhandapani/vlab/mozhi/model-server/model-store/
   type: DirectoryOrCreate
 nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - minikube
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store-claim
  namespace: mozhi
spec:
  storageClassName: local-storage
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 1Gi