apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: local-storage
    namespace: mozhi
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: minio-pv-volume-2
#  namespace: mozhi
#  labels:
#    type: local
#spec:
#  persistentVolumeReclaimPolicy: Delete
#  storageClassName: local-storage
#  capacity:
#    storage: 256Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/media/working/minio-volume/2"
#---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-store-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi


