[developement]
[developement.pl_trainer]
max_epochs=1
gpus=1
accumulate_grad_batches=4
model_root_dir="~/.mozhi/models/pytorch/"
log_root_dir="~/.mozhi/logs/pytorch/"
preprocessor_root_dir="~/.mozhi/preprocessor/"
[developement.hf_trainer]
max_epochs=10
learning_rate=2e-5
batch_size=8
model_root_dir="~/.mozhi/models/hf/"
[staging]

[production]
